### ISSUE TITLE
TestRailException: Field :custom_browser_type is a required field.

### ISSUE THREAD

**Issue by cwillyosorto** [dlenroc/node-testrail-api#39]
Hi, I'm a little bit stuck with this error and I can't find any information on other place, so maybe you can help me, I juts got this error when I'm trying to use the `addResultToCase()` call, here's the code:

`api.addResultForCase(run.id, testCase[0].id, {status_id: testStatus.id, comment: dataBrokerTest.output})`

Then I got the error on console: 

`TestRailException: Field :custom_browser_type is a required field. at p._api (/Users/wosorto/Documents/Projects/fusiontestrail-connector/node_modules/@dlenroc/testrail/dist/TestRail.node.js:1:8519)`

**Comment by dlenroc** [comment]
This error comes from TestRail and means that you or someone else configured a custom result field called `custom_browser_type` and marked it as a required field.

You can read more about this in [Configuring custom fields](https://www.gurock.com/testrail/docs/user-guide/howto/fields) documentation. 

Also, if you are not very familiar with the TestRail API, I can also suggest going through the [TestRail API Reference Guide](https://www.gurock.com/testrail/docs/api).

---

So you need to either just send it

```typescript
api.addResultForCase(run.id, testCase[0].id, {
  status_id: testStatus.id,
  comment: dataBrokerTest.output,
  custom_browser_type: /* value for your custom type, I do not know what type it has */
})
```

Or mark it as an optional field in the admin configuration and then add the result without it

```typescript
api.addResultForCase(run.id, testCase[0].id, {
  status_id: testStatus.id,
  comment: dataBrokerTest.output
})
```

PS: @cwillyosorto I will close this issue because it is not related to the testrail client but more to TestRail itself which has https://discuss.gurock.com/ and support that can answer any questions related to their product.
