### ISSUE TITLE
methods dont work unless they are public

### ISSUE THREAD

**Issue by margaritluch** [dlenroc/node-testrail-api#54]
I can only make methods from Testrail.ts to work when i edit them and make them public. Am I doing something wrong or how come it cant be used without changing the testrail.ts code?

**Comment by dlenroc** [comment]
@margaritluch can you elaborate more about the node js version, editor, minimal reproducible sample, and error/problem you get?
> After publishing `testrail.ts` is only used for completion/validation by editors -- which is well supported by VSCode and JetBrains IDEs.
>
> Code logic itself is used from `dist` folder which contains compiled TS for different targets: CommonJS / ESM / UMD.
>
> | CommonJS Syntax     | ESM Syntax |
> | ----------- | ----------- |
> | ![-](https://user-images.githubusercontent.com/18662534/175768985-fe6518a4-416e-4db7-8d26-da60de3bce98.png)    | ![-](https://user-images.githubusercontent.com/18662534/175768810-e5a89a27-a99a-473d-a99c-2b7d0a72510a.png)  |
>
> I myself use this library in browser and from JS/TS projects and have not encountered any problems with modifiers in TS

I assume that your problem is not related to `public` modifier
> https://www.typescriptlang.org/docs/handbook/2/classes.html#public
> The default visibility of class members is public. A public member can be accessed anywhere:

but something else: a bug / lack in the editor you are using, or a misuse of the programming language/editor/bundlers.

PS: This is the best answer I can give, given the missing context in the title/description.
