### ISSUE TITLE
I'm experiencing strange issue when working with safari

### ISSUE THREAD

**Issue by margaritluch** [dlenroc/node-testrail-api#60]
https://stackoverflow.com/questions/73093349/nested-testrail-api-calls-used-to-upload-test-results-to-testrail-fail-after-usi

**Comment by dlenroc** [comment]
@margaritluch please don't open more issues without a reproducible example.

----

I don't use TestCafe but if it works like other test runners then it doesn't run in the **browser** but on the user's **computer** (and simply process/publish results - so It **should not be browser-specific otherwise is a design issue**).
> If it really runs in the browser (and CORS are somehow bypassed - patched custom server or through a proxy) then the most probable TestRail Test Case reporter maintainer didn't bundle the final code for a specific browser.

Anyway, such issues should be handled by the TestRail Test Case reporter maintainer, or by TestRail which provides customer support if the extension maintainer has problems with their API.


**PS:** TestRail itself blocks requests coming from browsers through CORS (only requests coming from TestRail instance domain and from [UI scripts](https://support.gurock.com/hc/en-us/articles/7344009893908-UI-scripts-introduction) are allowed to pass - browser inspector should show if this is the case).

**Comment by margaritluch** [comment]
@dlenroc  Thank you for quick response :) I'll try to contact Testrail customer support and find out whats wrong
